name: Armor Control
author: Staartvin
website: http://dev.bukkit.org/server-mods/armor-control/
main: Staartvin.ArmorControl.ArmorControl
version: 1.5
description: Control players on wearing armor or using weapons/tools by experience.
permissions:
    armorcontrol.exempt:
        description: A player with this permission is not bound to any armor restrictions.
        default: false
    toolcontrol.exempt:
        description: A player with this permission is not bound to any tool restrictions.
        default: false
    weaponcontrol.exempt:
        description: A player with this permission is not bound to any weapons restrictions.
        default: false
    armorcontrol.reload:
        description: A player with this permission is allowed to perform /ac reload.
        default: op
    armorcontrol.add:
        description: A player with this permission is allowed to add a custom ID with /ac add.
        default: op
commands:
    ac:
      description: Master command of Armor Control.
      usage: /<command> <argument>
      aliases: [armorcontrol]