name: Armor Control
author: Staartvin
website: http://dev.bukkit.org/server-mods/armor-control/
main: Staartvin.ArmorControl.ArmorControl
version: 1.2
description: Control players on wearing armor by experience.
permissions:
    armorcontrol.exempt:
        description: A player with this permission is not bound to any armor restrictions.
        default: op
    toolcontrol.exempt:
        description: A player with this permission is not bound to any tool restrictions.
        default: op
    weaponcontrol.exempt:
        description: A player with this permission is not bound to any weapons restrictions.
        default: op
commands: